### ISSUE TITLE
WebSocketHandlerMixin assertion error

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/nbserverproxy#16]
I started a web service via `python -m http.server 8001` and visited proxy/8001. The user server errored with 503 and the log file contained:

```
[E 2018-01-24 00:10:12.962 SingleUserNotebookApp http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/srv/conda/envs/data100/lib/python3.6/site-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/srv/conda/envs/data100/lib/python3.6/site-packages/tornado/httpserver.py", line 314, in finish
        self.delegate.finish()
      File "/srv/conda/envs/data100/lib/python3.6/site-packages/tornado/routing.py", line 251, in finish
        self.delegate.finish()
      File "/srv/conda/envs/data100/lib/python3.6/site-packages/tornado/web.py", line 2097, in finish
        self.execute()
      File "/srv/conda/envs/data100/lib/python3.6/site-packages/tornado/web.py", line 2117, in execute
        **self.handler_kwargs)
      File "/srv/conda/envs/data100/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 21, in __init__
        assert WebSocketHandlerMixin in bases
    AssertionError
```

**Comment by betatim** [comment]
I think #15 might fix this.

**Comment by ryanlovett** [comment]
Thanks @betatim! Merged.

**Comment by betatim** [comment]
If it did fix it, time to close this?

**Comment by ryanlovett** [comment]
Just confirmed, thanks!
