### ISSUE TITLE
PyPI wheel indicates Python 2 support

### ISSUE THREAD

**Issue by jjhelmus** [jupyterhub/nbserverproxy#27]
The wheel on PyPI (nbserverproxy-0.7-py2.py3-none-any.whl ) is marked as supporting Python 2 which is not true.  Installing in a Python 2.7 environment via pip succeeds but enabling the server extension fails with a SyntaxError:

```
$ python -V
Python 2.7.14 :: Anaconda, Inc.
$ jupyter serverextension enable --py nbserverproxy
Traceback (most recent call last):
  File "/home/jhelmus/anaconda3/envs/ttt/bin/jupyter-serverextension", line 11, in <module>
    sys.exit(main())
  File "/home/jhelmus/anaconda3/envs/ttt/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/jhelmus/anaconda3/envs/ttt/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/jhelmus/anaconda3/envs/ttt/lib/python2.7/site-packages/notebook/serverextensions.py", line 293, in start
    super(ServerExtensionApp, self).start()
  File "/home/jhelmus/anaconda3/envs/ttt/lib/python2.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/jhelmus/anaconda3/envs/ttt/lib/python2.7/site-packages/notebook/serverextensions.py", line 210, in start
    self.toggle_server_extension_python(arg)
  File "/home/jhelmus/anaconda3/envs/ttt/lib/python2.7/site-packages/notebook/serverextensions.py", line 199, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/home/jhelmus/anaconda3/envs/ttt/lib/python2.7/site-packages/notebook/serverextensions.py", line 327, in _get_server_extension_metadata
    m = import_item(module)
  File "/home/jhelmus/anaconda3/envs/ttt/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/home/jhelmus/anaconda3/envs/ttt/lib/python2.7/site-packages/nbserverproxy/__init__.py", line 1, in <module>
    from nbserverproxy.handlers import setup_handlers
  File "/home/jhelmus/anaconda3/envs/ttt/lib/python2.7/site-packages/nbserverproxy/handlers.py", line 53
    async def get(self, *args, **kwargs):
            ^
SyntaxError: invalid syntax
```
It would be nice if the incompatibility with Python 2 was expressed in a more obvious manner.

**Comment by ryanlovett** [comment]
Fixed, thanks! I've deleted the universal wheel, uploaded one for python3, and updated the README.md.

**Comment by jjhelmus** [comment]
Thanks for the quick update.
