### ISSUE TITLE
Websocket can't initialize with Tornado 4.5.1

### ISSUE THREAD

**Issue by saurfang** [jupyterhub/nbserverproxy#32]
Running this with `nbrsessionproxy` and got the following exception when trying to establish a websocket connection:

```
[I 2018-05-07 21:32:51.808 sen_fang handlers:136] Trying to establish websocket connection to ws://127.0.0.1:60981/p/6758/websocket/
[E 2018-05-07 21:32:51.808 sen_fang ioloop:638] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f6d9c9598c8>, <tornado.concurrent.Future object at 0x7f6d9cc159e8>)
    Traceback (most recent call last):
      File "/opt/conda/envs/py36/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
        ret = callback()
      File "/opt/conda/envs/py36/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/opt/conda/envs/py36/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
        future.result()
      File "/opt/conda/envs/py36/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/opt/conda/envs/py36/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "<string>", line 6, in _wrap_awaitable
      File "/opt/conda/envs/py36/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 140, in start_websocket_connection
        on_message_callback=message_cb, on_ping_callback=ping_cb)
      File "/opt/conda/envs/py36/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 55, in pingable_ws_connect
        on_ping_callback=on_ping_callback)
      File "/opt/conda/envs/py36/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 35, in __init__
        super().__init__(**kwargs)
      File "/opt/conda/envs/py36/lib/python3.6/site-packages/tornado/websocket.py", line 1076, in __init__
        104857600, self.tcp_client, 65536, 104857600)
      File "/opt/conda/envs/py36/lib/python3.6/site-packages/tornado/simple_httpclient.py", line 196, in __init__
        self.start_time = io_loop.time()
    AttributeError: 'NoneType' object has no attribute 'time'
```

It looks like because `io_loop` is set to `None` but Tornado expects to use it at here:
https://github.com/jupyterhub/nbserverproxy/commit/beefebc52fc57f55ab34d463ff21b60682537749#diff-ca755767ba44dc77b227f5de4d62ed08R34
https://github.com/tornadoweb/tornado/blob/branch4.5/tornado/websocket.py#L1082
https://github.com/tornadoweb/tornado/blob/branch4.5/tornado/simple_httpclient.py#L196

**Comment by ryanlovett** [comment]
Thanks for the report.

I believe 1e0ce33 fixes this -- tested on binder. Can you confirm?

**Comment by saurfang** [comment]
Confirmed it is fixed. Thanks for the quick turnaround!
