### ISSUE TITLE
Client sent subprotocols: []

### ISSUE THREAD

**Issue by jakirkham** [jupyterhub/nbserverproxy#47]
Got this exception recently when using this to view the Dask Distributed Dashboard using nbserverproxy while running a Jupyter Notebook.

```
Client sent subprotocols: []
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=IndexError('list index out of range',)>
Traceback (most recent call last):
  File "/opt/conda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda3/lib/python3.6/site-packages/tornado/websocket.py", line 721, in _accept_connection
    self.selected_subprotocol = self.handler.select_subprotocol(subprotocols)
  File "/opt/conda3/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 300, in select_subprotocol
    return subprotocols[0]
IndexError: list index out of range
```

**Comment by jakirkham** [comment]
Possibly. Missed that when searching the tracker.

**Comment by jakirkham** [comment]
Yep, the recent release seemed to solve it.
